### PR TITLE
Fix#12 #10 

### LINKED ISSUE #10: Custom highlighting not working
#### Steps to Reproduce:
1. Set the following config:
```
return {
  "mei28/luminate.nvim",
  event = "VeryLazy",
  branch = "fix#7",
  config = function()
    require("luminate").setup({
      duration = 200,
      yank = {
        hlgroup = "IncSearch",
        guibg = "#f7c67f",
        fg = "#1a1c2c",
      },
    })
  end,
}
```
2. Open a buffer and yank a text.

#### Expected Behavior: 
The yanked text should be highlighted.

#### Actual Behavior:
The yanked text is not highlighted.

#### Additional Information:
Besides yanking, undo, redo, and paste are also not highlighted. However, if I remove the custom highlighting section in the config, all things are highlighted with the default colours.

#### Environment:
- **Neovim version:** 0.9.4
- **This repo commit ID:** 3291f13

### LINKED ISSUE #12: Duration does not seem to change
I changed the duration in my user config but it doesn't seem to do anything. I set it `1` and expected it to be super fast but it did not.

### PR DESCRIPTION
**Pull request by mei28**
close #10 
close #12 

Hi, @agaro1121

Thank you for your report. The bugs were caused by my refactoring. I have fixed them; could you please try it again?

If there are no issues, I will merge it.

```lua
{
'mei28/luminate.nvim',
branch = "fix#12",
...
}
```

### CODE REVIEW

**Comment by shauryagoel** [comment]
Hi @mei28, I tried this and duration still does not seem to work correctly. #10 seems to be solved, however.

**Comment by mei28** [comment]
luminate#12

@shauryagoel  
Thank you check it.
It seems to be healing normally as far as I run it, is there any difference?

**Comment by shauryagoel** [comment]
Sorry for creating noise. My lazvim was using an old commit for the fix#12 branch. #12 is solved as well now. 
Is `hlgroup` still required in the config?

**Comment by mei28** [comment]
The default values are applied, so users do not need to configure them. However, users can change these settings if they wish to customize them.

**Pull request merged**
